service: serverlessapi

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    darkSkyApiKey: ${env:DARKSKY_API_KEY}
    geocodeAccessToken: ${env:GEOCODE_ACCESS_TOKEN}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
         path: helloworld
         method: post
